### ISSUE TITLE
Compatible X96 Max PlusQ1 ??

### ISSUE THREAD

**Issue by tv4you2016** [danboid/meson-sm1-sei610-qca9377-bt#1]
hello my box and:
X96 Max PlusQ1. Without chip 1000Mb. LAN 100, Cdtech 4761743 radio module and two antennas. photo here

![21842142](https://user-images.githubusercontent.com/83761813/158480796-950a872e-8996-4cc1-b9da-e58d4249636e.jpg)

![IMG_20210109_154247](https://user-images.githubusercontent.com/83761813/158480806-9b3b4f15-7c7f-4e06-b924-a63c5ffdd8fe.jpg)

and compatible with this dtb??

**Comment by danboid** [comment]
I have no idea sorry.

I have just now uploaded a Manjaro kernel package that works with this dtb so if you can install the kernel and dtb you can see if it works?

https://github.com/danboid/meson-sm1-sei610-qca9377-bt/releases/tag/kernel

**Comment by tv4you2016** [comment]
Ok 

I will use this:
(https://github.com/ophub/amlogic-s9xxx-armbian/releases/tag/Armbian_Aml_focal_03.15.1359)
Armbian_22.05.0_Aml_s905x_focal_5.15.28_2022.03.15.1342.img.gz

do you see any harm in that?

**Comment by danboid** [comment]
I am running ophubs Armbian on my X96 Air now but you won't be able to use my dtb file unless you build Linux 5.12 for Armbian.
